services:
  database:
    image: postgres
    ports:
      - 5431:5432
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379
    env_file:
      - .env

  frontend:
    image: frontend:latest
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - backend
    restart: always

  backend:
    image: backend:latest
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
      - redis
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

#  mailservice:
#    image: axigen/axigen
#    volumes:
#      - ./mail_data:/axigen/var
#      - ./mail_opt:/var/opt
#      - ./mail_opt2:/axigen/opt
#    ports:
#      - 9443:9443
#      - 993:993
#      - 995:995
#      - 25:25
#      - 465:465
#      - 9000:9000
#      - 7000:7000

#  nginx:
#    image: nginx
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./conf.d:/etc/nginx/conf.d
#      - /etc/letsencrypt:/etc/letsencrypt:ro
#      - /etc/letsencrypt:/etc/nginx/ssl
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  bot:
    image: logistic_bot:latest
    restart: always
    env_file:
      - .env


volumes:
  pgadmin-data: