services:
  database:
    image: postgres
    ports:
      - 5431:5432
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - 6379:6379
    env_file:
      - .env