"""added_user_organization

Revision ID: 107b04f2194b
Revises: ecc42f08ec1e
Create Date: 2024-03-23 18:55:30.978841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107b04f2194b'
down_revision: Union[str, None] = 'ecc42f08ec1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('user', sa.Column('is_organization_user', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'user', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'is_organization_user')
    op.drop_column('user', 'organization_id')
    # ### end Alembic commands ###
