"""added-order-fields

Revision ID: 437df2f219fa
Revises: f71be22c79a8
Create Date: 2023-12-18 11:55:20.790355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437df2f219fa'
down_revision: Union[str, None] = 'f71be22c79a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payedSum', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('shippedSum', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('state', sa.String(), nullable=True))
    op.add_column('order', sa.Column('sum', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('moysklad_invoice_out_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('moysklad_invoice_item_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'moysklad_invoice_item_id')
    op.drop_column('order_items', 'quantity')
    op.drop_column('order_items', 'price')
    op.drop_column('order', 'moysklad_invoice_out_id')
    op.drop_column('order', 'sum')
    op.drop_column('order', 'state')
    op.drop_column('order', 'shippedSum')
    op.drop_column('order', 'payedSum')
    # ### end Alembic commands ###
