"""added_meta

Revision ID: 8de8a20902b2
Revises: 93cf4ca5b90e
Create Date: 2023-12-14 22:54:28.395369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de8a20902b2'
down_revision: Union[str, None] = '93cf4ca5b90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('moysklad_product_folder_meta', sa.JSON(), nullable=True))
    op.add_column('order', sa.Column('moysklad_customer_order_id', sa.UUID(), nullable=True))
    op.add_column('order', sa.Column('moysklad_customer_order_meta', sa.JSON(), nullable=True))
    op.add_column('order_items', sa.Column('moysklad_product_meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'moysklad_product_meta')
    op.drop_column('order', 'moysklad_customer_order_meta')
    op.drop_column('order', 'moysklad_customer_order_id')
    op.drop_column('order', 'moysklad_product_folder_meta')
    # ### end Alembic commands ###
