"""order_id_change

Revision ID: 936e70921428
Revises: b44b12e2e087
Create Date: 2024-01-05 19:09:53.864555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936e70921428'
down_revision: Union[str, None] = 'b44b12e2e087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM message")
    op.execute("DELETE FROM chat_room")
    op.drop_constraint("chat_room_order_id_fkey", "chat_room")

    op.drop_column("chat_room", "order_id")
    op.add_column("chat_room", sa.Column("order_id", sa.UUID(), nullable=True))

    op.add_column('order', sa.Column('moysklad_customer_order_state', sa.String(), nullable=True))
    op.drop_column('order', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order', 'moysklad_customer_order_state')
    op.create_foreign_key('chat_room_order_id_fkey', 'chat_room', 'order', ['order_id'], ['id'])
    op.alter_column('chat_room', 'order_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
