"""added_meta

Revision ID: 93cf4ca5b90e
Revises: f2d48f0f64e1
Create Date: 2023-12-14 22:48:36.883643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cf4ca5b90e'
down_revision: Union[str, None] = 'f2d48f0f64e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('moysklad_product_folder_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('moysklad_product_id', sa.UUID(), nullable=True))
    op.add_column('user', sa.Column('moysklad_counterparty_meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'moysklad_counterparty_meta')
    op.drop_column('order_items', 'moysklad_product_id')
    op.drop_column('order', 'moysklad_product_folder_id')
    # ### end Alembic commands ###
