"""added chat

Revision ID: 9f2030e4a32f
Revises: ec89ac56f621
Create Date: 2023-12-23 04:52:25.045634

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2030e4a32f'
down_revision: Union[str, None] = 'ec89ac56f621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('client_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.create_foreign_key(None, 'chat_room', 'user', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_room', type_='foreignkey')
    op.drop_column('chat_room', 'client_id')
    # ### end Alembic commands ###
