"""added_moysklad_user

Revision ID: a91fd5584af4
Revises: 09c43e5db9e1
Create Date: 2023-12-13 23:07:58.983656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91fd5584af4'
down_revision: Union[str, None] = '09c43e5db9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('moysklad_counterparty_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'moysklad_counterparty_id')
    # ### end Alembic commands ###
