"""change_chat

Revision ID: b44b12e2e087
Revises: c39acde61fce
Create Date: 2023-12-27 01:31:17.973668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44b12e2e087'
down_revision: Union[str, None] = 'c39acde61fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_room', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_room', type_='foreignkey')
    op.drop_column('chat_room', 'order_id')
    # ### end Alembic commands ###
