"""added chat

Revision ID: c39acde61fce
Revises: 37863e2965d8
Create Date: 2023-12-23 05:10:02.535743

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39acde61fce'
down_revision: Union[str, None] = '37863e2965d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('from_user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.add_column('message', sa.Column('to_chat_room_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['from_user_id'], ['id'])
    op.create_foreign_key(None, 'message', 'chat_room', ['to_chat_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'to_chat_room_id')
    op.drop_column('message', 'from_user_id')
    # ### end Alembic commands ###
