"""added unique

Revision ID: ef73eaab97ae
Revises: 538f1ae51900
Create Date: 2024-01-18 22:17:01.325987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef73eaab97ae'
down_revision: Union[str, None] = '538f1ae51900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('privoz_order', 'privoz_order',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('privoz_order', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privoz_order', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('privoz_order', 'privoz_order',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
