$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

$ruffTargets = @(
    "config.py",
    "errors.py",
    "main.py",
    "alembic/env.py",
    "alembic/versions/c8f2a4e6d901_order_chat_delivery.py",
    "alembic/versions/b7e1d3a9f4c2_add_user_addresses.py",
    "db/postgres.py",
    "db/redis.py",
    "db/address_repository.py",
    "db/repository.py",
    "db/link_preview_repository.py",
    "db/models/addresses.py",
    "db/models/order_chat.py",
    "db/moysklad_order_chat_repository.py",
    "db/order_chat_repository.py",
    "db/schemas/chat.py",
    "db/schemas/addresses.py",
    "db/schemas/link_preview.py",
    "db/schemas/orders.py",
    "dependecies/addresses.py",
    "dependecies/chat.py",
    "dependecies/link_preview.py",
    "dependecies/orders.py",
    "dependecies/order_chat.py",
    "bot/sender.py",
    "manager/chat.py",
    "manager/addresses.py",
    "manager/chat_files.py",
    "manager/chat_outbox.py",
    "manager/chat_realtime.py",
    "manager/chat_storage.py",
    "manager/link_preview.py",
    "manager/moysklad.py",
    "manager/phone_numbers.py",
    "manager/moysklad_order_chat.py",
    "manager/order_changes.py",
    "manager/order_creation.py",
    "manager/order_chat.py",
    "manager/order_chat_format.py",
    "manager/bitrix.py",
    "manager/privoz_order.py",
    "manager/production_config.py",
    "manager/users.py",
    "routes/bitrix.py",
    "routes/addresses.py",
    "routes/chat.py",
    "routes/integration/order_chat_webhook.py",
    "routes/link_preview.py",
    "routes/notifications.py",
    "routes/orders.py",
    "scripts/check_production_config.py",
    "scripts/register_moysklad_order_chat_webhook.py",
    "moysklad_webhooks_creator.py",
    "tests"
)

& ".\.venv\Scripts\python.exe" -m ruff check @ruffTargets
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
& ".\.venv\Scripts\python.exe" -m pytest tests -q
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
